### PR TITLE
fix page names that contain dot

### LINKED ISSUE #2555: Hugo 0.17 regression with page names that contain dot
On Hugo 0.16 the pages with dot in name were rendering correctly.

With Hugo 0.17 pages with dot in their name won't render. With `hugo server` I get only 

```
<pre>
</pre>
```

in output.
However when doing a build of site with `hugo` the name of page with dot get stripped down to the first dot. The content of the page is correct though.

### PR DESCRIPTION
**Pull request by vyuh**
changes:

- in hugolib/page.go, `func permalink` and `func TargetPath`
      Fixed the attempt to *replace* the extension of something
      that was *already* a basename (without extension) .
- in source/file.go, `func NewFile`
      added check for allowed languages before translating filename

Fixes #2555

### CODE REVIEW

**Comment by vyuh** [comment]
I adding the following language related things to `config.toml` as shown in https://gohugo.io/content/multilingual/:
 ```toml
 [Languages]
 [Languages.en]
 weight = 1
 title = "English"
 [Languages.en.blackfriday]
 angledQuotes = false

 [Languages.fr]
 weight = 2
 title = "Français"
 [Languages.fr.Taxonomies]
 plaque = "plaques"
 ```
I then built the site after adding some files with troublesome names:
```sh
$GOPATH/bin/hugo new post/moo.0.7.74823478.md
$GOPATH/bin/hugo new post/moo.0.7.fr.md
$GOPATH/bin/hugo new post/moo.0.7.en.md
$GOPATH/bin/hugo new post/moo.0.7.es.md
$GOPATH/bin/hugo server -D
```
The following permalinks were found accessible for the content pages created above, respectively:
- http://localhost:1313/post/moo.0.7.74823478/
- http://localhost:1313/fr/post/moo.0.7/
- http://localhost:1313/post/moo.0.7/
- http://localhost:1313/post/moo.0.7.es/

Relevant part of generated website:
```text
public/
├── en
│   ├── index.html
│   └── sitemap.xml
├── fr
│   ├── index.html
│   ├── index.xml
│   ├── post
│   │   ├── index.html
│   │   ├── index.xml
│   │   ├── moo.0.7
│   │   │   └── index.html
│   │   └── page
│   │       └── 1
│   │           └── index.html
│   └── sitemap.xml
├── index.html
├── index.xml
├── post
│   ├── index.html
│   ├── index.xml
│   ├── moo.0.7
│   │   └── index.html
│   ├── moo.0.7.74823478
│   │   └── index.html
│   ├── moo.0.7.es
│   │   └── index.html
│   └── page
│       └── 1
│           └── index.html
└──  sitemap.xml
```
This is all the testing I have done. Things were working as I expected and nothing was visibly broken. File name translation is now only done for languages specified in the `Languages` table in configuration file. Please test other use cases if this is not sufficient.

@abourget

File: source/file.go [hunk 1]
```diff
@@ -126,11 +126,14 @@ func NewFile(relpath string) *File {
 	f.ext = strings.TrimPrefix(filepath.Ext(f.LogicalName()), ".")
 	f.baseName = helpers.Filename(f.LogicalName())
 
-	f.lang = strings.TrimPrefix(filepath.Ext(f.baseName), ".")
-	if f.lang == "" {
+	lang := strings.TrimPrefix(filepath.Ext(f.baseName), ".")
+	if _, ok := viper.GetStringMap("Languages")[lang]; lang == "" || !ok {
```
Comment (bep) [inline source/file.go]: All the rest of viper.Get... in Hugo now camelCase keys, so we might as well be pedantic about it. Other than that this looks good.

Comment (vyuh) [inline source/file.go]: I took that verbatim from https://gohugo.io/content/multilingual/, I've come to know only now that case of keys does not matter. 😛
I've pushed the improved version.

**Comment by miltador** [comment]
Thanks @vyuh. Just have checked this out, works like a charm!

**Comment by bep** [comment]
For future reference: Notice the capital first char in the commit message title
