### PR TITLE
hugolib: Clean up redundant frontmatter error logging

### LINKED ISSUE #3157: Don't repeat ERROR on front matter parse error
I was publishing a new page to my simple hugo site when I got the following error:

```
ERROR 2017/03/09 22:01:28 Error parsing page meta data for post/post.md
ERROR 2017/03/09 22:01:28 (4, 9): keys cannot contain new lines
ERROR 2017/03/09 22:01:28 (4, 9): keys cannot contain new lines
Error: Error building site: Errors reading pages: Error:(4, 9): keys cannot contain new lines for post.md
```

After some time I realized it was the frontmatter in the document. Turns out (4, 9) means "Row 4, column 9"

The fix was s/False/false/. Seems like Hugo should have a better error for this. I'll see what I can do to add this feature tomorrow, but I figured I should post this for now.

### PR DESCRIPTION
**Pull request by moorereason**
Fixes #3157

### CODE REVIEW

File: hugolib/page.go [hunk 1]
```diff
@@ -1394,9 +1394,7 @@ func (p *Page) parse(reader io.Reader) error {
 	meta, err := psr.Metadata()
 	if meta != nil {
 		if err != nil {
-			p.s.Log.ERROR.Printf("Error parsing page meta data for %s", p.File.Path())
-			p.s.Log.ERROR.Println(err)
-			return err
+			return fmt.Errorf("failed to parse page metadata for %s: %s", p.File.Path(), err)
```
Comment (tmcarr) [inline hugolib/page.go]: Wow, had I known it was this easy, Id've submitted the PR myself!
